[phases.setup]
nixPkgs = ["python39", "nodejs-18_x", "python39Packages.pip"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && REACT_APP_API_URL=/api npm run build",
    "mkdir -p backend/static",
    "cp -r frontend/build/* backend/static/ || true"
]

[start]
cmd = "cd backend && gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT" 